// <auto-generated />
using System;
using CourseOutcome.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseOutcome.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseOutcome.Models.Question", b =>
                {
                    b.Property<string>("QId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Qtext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("QId");

                    b.HasIndex("SId");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            QId = "OS1",
                            Qtext = "Are you able to Explain the structure and functions of Operating Systems along with their components, types and working.",
                            SId = "MCA-105"
                        },
                        new
                        {
                            QId = "OS2",
                            Qtext = "Are you able to Make use of appropriate Linux commands for Memory Management, File Management and Directory Management.",
                            SId = "MCA-105"
                        },
                        new
                        {
                            QId = "OS3",
                            Qtext = "Are you able to Analyze the performance of different Scheduling algorithms along with the policies for Concurrency and Deadlock management.",
                            SId = "MCA-105"
                        },
                        new
                        {
                            QId = "OS4",
                            Qtext = "Are you able to Elaborate the System Calls for Process management and File Management.",
                            SId = "MCA-105"
                        },
                        new
                        {
                            QId = "DBMS1",
                            Qtext = "Are you able to Explain the various database components, models, DBMS architecture and Database Security",
                            SId = "MCA-107"
                        },
                        new
                        {
                            QId = "DBMS2",
                            Qtext = "Are you able to Apply relational database theory to construct relational algebra expression, tuple and domain relation expression for SQL queries.",
                            SId = "MCA-107"
                        },
                        new
                        {
                            QId = "DBMS3",
                            Qtext = "Are you able to Construct advanced SQL queries on data and apply Procedural abilities through PL/SQL.",
                            SId = "MCA-107"
                        },
                        new
                        {
                            QId = "DBMS4",
                            Qtext = "Are you able to Examine the use of normalization and functional dependency for database design.",
                            SId = "MCA-107"
                        },
                        new
                        {
                            QId = "DBMS5",
                            Qtext = "Are you able to Appraise the concepts of transaction, concurrency control and recovery in databases.",
                            SId = "MCA-107"
                        },
                        new
                        {
                            QId = "OOPJ1",
                            Qtext = "Are you able to Illustrate the Object-Oriented paradigm, Java language constructs and JVM internal architecture.",
                            SId = "MCA-109"
                        },
                        new
                        {
                            QId = "OOPJ2",
                            Qtext = "Are you able to Apply the concepts of exception handling, multithreading, and collection framework.",
                            SId = "MCA-109"
                        },
                        new
                        {
                            QId = "OOPJ3",
                            Qtext = "Are you able to Analyze the use of event handling and JFC based toolkit in creating GUI-based computing solutions.",
                            SId = "MCA-109"
                        },
                        new
                        {
                            QId = "OOPJ4",
                            Qtext = "Are you able to Design database enabled client-server applications using JDBC, RMI, I/O operations, network programming and relevant concepts.",
                            SId = "MCA-109"
                        },
                        new
                        {
                            QId = "OOPJ5",
                            Qtext = "Are you able to Elaborate the functional programming concepts introduced in Java 8 and beyond.",
                            SId = "MCA-109"
                        },
                        new
                        {
                            QId = "CNL1",
                            Qtext = "Are you able to Interpret suitable Network Simulator",
                            SId = "MCA-161"
                        },
                        new
                        {
                            QId = "CNL2",
                            Qtext = "Are you able to Apply network configuration skills to design specific network scenarios.",
                            SId = "MCA-161"
                        },
                        new
                        {
                            QId = "CNL3",
                            Qtext = "Are you able to Make use of various connecting devices and LAN connectivity to build networks.",
                            SId = "MCA-161"
                        },
                        new
                        {
                            QId = "CNL4",
                            Qtext = "Are you able to Simulate the working and analyze the performance of various communication protocols.",
                            SId = "MCA-161"
                        },
                        new
                        {
                            QId = "CNL5",
                            Qtext = "Are you able to Evaluate routing in the networks and compare different routing algorithms",
                            SId = "MCA-161"
                        },
                        new
                        {
                            QId = "CNL6",
                            Qtext = "Are you able to Work in teams to design networks for real life scenarios by applying the concepts of all the layered architecture.",
                            SId = "MCA-161"
                        },
                        new
                        {
                            QId = "OSL1",
                            Qtext = "Are you able to Build the Linux operating system and configure it.",
                            SId = "MCA-163"
                        },
                        new
                        {
                            QId = "OSL2",
                            Qtext = "Are you able to Discover Linux commands for working with Linux Environment",
                            SId = "MCA-163"
                        },
                        new
                        {
                            QId = "OSL3",
                            Qtext = "Are you able to Appraise the Process Management algorithms, Process Management system calls, Inter Process Communication and CPU Scheduling algorithms",
                            SId = "MCA-163"
                        },
                        new
                        {
                            QId = "OSL4",
                            Qtext = "Are you able to Create programs using systems calls for memory management and File Management in C programming, also simulate Deadlock avoidance algorithm using C.",
                            SId = "MCA-163"
                        },
                        new
                        {
                            QId = "DBMSL1",
                            Qtext = "Are you able to Translate an information model into a relational database schema and to implement the schema using RDBMS",
                            SId = "MCA-165"
                        },
                        new
                        {
                            QId = "DBMSL2",
                            Qtext = "Are you able to Apply advanced SQL features like views, indexes, synonyms, etc. for database management",
                            SId = "MCA-165"
                        },
                        new
                        {
                            QId = "DBMSL3",
                            Qtext = "Are you able to Analyze PL/SQL structures like functions, procedures, cursors and triggers for database applications.",
                            SId = "MCA-165"
                        },
                        new
                        {
                            QId = "DBMSL4",
                            Qtext = "Are you able to Examine database administration concepts like GRANT, REVOKE etc. through SQL commands.",
                            SId = "MCA-165"
                        },
                        new
                        {
                            QId = "DBMSL5",
                            Qtext = "Are you able to Work in teams to design solutions for real world problems/case studies by creating efficient database schema.",
                            SId = "MCA-165"
                        },
                        new
                        {
                            QId = "OOPJL1",
                            Qtext = "Are you able to Apply Object-Oriented and Java language constructs for creating Java programs.",
                            SId = "MCA-167"
                        },
                        new
                        {
                            QId = "OOPJL2",
                            Qtext = "Are you able to Make use of exception handling, multithreading, and collection framework for constructing effective solutions.",
                            SId = "MCA-167"
                        },
                        new
                        {
                            QId = "OOPJL3",
                            Qtext = "Are you able to Inspect the use of event handling and JFC based toolkit for GUI-based computing solutions.",
                            SId = "MCA-167"
                        },
                        new
                        {
                            QId = "OOPJL4",
                            Qtext = "Are you able to Design database enabled client-server applications using JDBC, RMI, I/O operations, network programming and relevant concepts.",
                            SId = "MCA-167"
                        },
                        new
                        {
                            QId = "OOPJL5",
                            Qtext = "Are you able to Elaborate the functional programming concepts introduced in Java 8 and beyond.",
                            SId = "MCA-167"
                        },
                        new
                        {
                            QId = "MP11",
                            Qtext = "Are you able to Apply acquired knowledge within the chosen technology for solution of specific problem.",
                            SId = "MCA-169"
                        },
                        new
                        {
                            QId = "MP12",
                            Qtext = "Are you able to Analyze the technical aspects of the chosen project through a systematic and comprehensive approach.",
                            SId = "MCA-169"
                        },
                        new
                        {
                            QId = "MP13",
                            Qtext = "Are you able to Deduct plausible solution for the technical aspects of the project.",
                            SId = "MCA-169"
                        },
                        new
                        {
                            QId = "MP14",
                            Qtext = "Are you able to Work as an individual or in teams to develop the technical project.",
                            SId = "MCA-169"
                        },
                        new
                        {
                            QId = "MP15",
                            Qtext = "Are you able to Create effective reports and documentation for all project related activities and solutions.",
                            SId = "MCA-169"
                        },
                        new
                        {
                            QId = "DS1",
                            Qtext = "Are you able to Choose appropriate discrete structures and combinatorics for basic problems.",
                            SId = "MCA-101"
                        },
                        new
                        {
                            QId = "DS2",
                            Qtext = "Are you able to Interpret and illustrate the basics of Group Theory.",
                            SId = "MCA-101"
                        },
                        new
                        {
                            QId = "DS3",
                            Qtext = "Are you able to Examine and infer mathematical logic and Boolean Algebra.",
                            SId = "MCA-101"
                        },
                        new
                        {
                            QId = "DS4",
                            Qtext = "Are you able to Evaluate applications of number theory.",
                            SId = "MCA-101"
                        },
                        new
                        {
                            QId = "DS5",
                            Qtext = "Are you able to Implement and create models for computer science problems by understanding the concepts of Graph Theory",
                            SId = "MCA-101"
                        },
                        new
                        {
                            QId = "FSDL1",
                            Qtext = "Are you able to apply concepts of DOM creation and rendering using React.js?",
                            SId = "FSDMCA-168"
                        },
                        new
                        {
                            QId = "FSDL2",
                            Qtext = "Are you able to make use of Node.js process model in given case studies?",
                            SId = "FSDMCA-168"
                        },
                        new
                        {
                            QId = "FSDL3",
                            Qtext = "Are you able to construct REST APIs for cross platform application development?",
                            SId = "FSDMCA-168"
                        },
                        new
                        {
                            QId = "FSDL4",
                            Qtext = "Are you able to create full stack applications using Angular.js and React. js?",
                            SId = "FSDMCA-168"
                        },
                        new
                        {
                            QId = "FSDL5",
                            Qtext = "Are you able to work in teams to develop applications with Node.js and MongoDB connectivity?",
                            SId = "FSDMCA-168"
                        },
                        new
                        {
                            QId = "DFS1",
                            Qtext = "Are you able to recall the different types of data structures?",
                            SId = "MCA-102"
                        },
                        new
                        {
                            QId = "DFS2",
                            Qtext = "Are you able to explain the fundamentals of an Abstract Data Type (ADT) ?",
                            SId = "MCA-102"
                        },
                        new
                        {
                            QId = "DFS3",
                            Qtext = "Are you able to analyze requirements with use cases?",
                            SId = "MCA-102"
                        },
                        new
                        {
                            QId = "DFS4",
                            Qtext = "Are you able to apply linear and nonlinear data structures to solve real time problems?",
                            SId = "MCA-102"
                        },
                        new
                        {
                            QId = "DFS5",
                            Qtext = "Are you able to appraise and determine the correct data structure for any given real-world problem?",
                            SId = "MCA-102"
                        },
                        new
                        {
                            QId = "DFS6",
                            Qtext = "Are you able to create innovative solutions for real world problems?",
                            SId = "MCA-102"
                        },
                        new
                        {
                            QId = "OOSE1",
                            Qtext = "Are you able to illustrate system modeling and architecture using UML?",
                            SId = "MCA-104"
                        },
                        new
                        {
                            QId = "OOSE2",
                            Qtext = "Are you able to apply suitable iterative process model?",
                            SId = "MCA-104"
                        },
                        new
                        {
                            QId = "OOSE3",
                            Qtext = "Are you able to analyze requirements with use cases?",
                            SId = "MCA-104"
                        },
                        new
                        {
                            QId = "OOSE4",
                            Qtext = "Are you able to appraise, analysis and design artifacts?",
                            SId = "MCA-104"
                        },
                        new
                        {
                            QId = "OOSE5",
                            Qtext = "Are you able to create domain models for analysis phase?",
                            SId = "MCA-104"
                        },
                        new
                        {
                            QId = "OOSE6",
                            Qtext = "Are you able to design object solutions with patterns and architectural layers",
                            SId = "MCA-104"
                        },
                        new
                        {
                            QId = "PP1",
                            Qtext = "Are you able to demonstrate knowledge of basic programming constructs in python?",
                            SId = "MCA-106"
                        },
                        new
                        {
                            QId = "PP2",
                            Qtext = "Are you able to illustrate string handling methods and user defined functions in python?",
                            SId = "MCA-106"
                        },
                        new
                        {
                            QId = "PP3",
                            Qtext = "Are you able to apply data structure primitives like lists, tuples, sets and dictionaries?",
                            SId = "MCA-106"
                        },
                        new
                        {
                            QId = "PP4",
                            Qtext = "Are you able to inspect file handling and object-oriented programming techniques?",
                            SId = "MCA-106"
                        },
                        new
                        {
                            QId = "PP5",
                            Qtext = "Are you able to evaluate and visualize the data using appropriate python libraries?",
                            SId = "MCA-106"
                        },
                        new
                        {
                            QId = "PP6",
                            Qtext = "Are you able to develop python applications with database connectivity operations?",
                            SId = "MCA-106"
                        },
                        new
                        {
                            QId = "FSD1",
                            Qtext = "Are you able to relate the basics of Javascript (JS) and ReactJS?",
                            SId = "MCA-114"
                        },
                        new
                        {
                            QId = "FSD2",
                            Qtext = "Are you able to apply the concepts of props and State Management in React JS?",
                            SId = "MCA-114"
                        },
                        new
                        {
                            QId = "FSD3",
                            Qtext = "Are you able to examine Redux and router with React JS?",
                            SId = "MCA-114"
                        },
                        new
                        {
                            QId = "FSD4",
                            Qtext = "Are you able to appraise Node JS environment and modular development?",
                            SId = "MCA-114"
                        },
                        new
                        {
                            QId = "FSD5",
                            Qtext = "Are you able to develop full stack applications using MongoDB?",
                            SId = "MCA-114"
                        },
                        new
                        {
                            QId = "SF1",
                            Qtext = "Are you able to identify the fundamentals of software testing and differentiate it from debugging?",
                            SId = "MCA-120"
                        },
                        new
                        {
                            QId = "SF2",
                            Qtext = "Are you able to apply knowledge of prioritization, and technical and logical dependencies to schedule test execution of a given set of test cases during development and regression testing?",
                            SId = "MCA-120"
                        },
                        new
                        {
                            QId = "SF3",
                            Qtext = "Are you able to appraise test tools, object-oriented software testing according to their purpose and the test activities they support?",
                            SId = "MCA-120"
                        },
                        new
                        {
                            QId = "SF4",
                            Qtext = "Are you able to develop test cases for given problem with respect to structural and functional techniques?",
                            SId = "MCA-120"
                        },
                        new
                        {
                            QId = "SF5",
                            Qtext = "Are you able to adapt in a cross-functional agile team to discuss principles and basic practices of Agile software development?",
                            SId = "MCA-120"
                        },
                        new
                        {
                            QId = "DM1",
                            Qtext = "Are you able to interpret digital marketing preliminaries?",
                            SId = "MCA-128"
                        },
                        new
                        {
                            QId = "DM2",
                            Qtext = "Are you able to build effective digital marketing strategies for different products and services?	",
                            SId = "MCA-128"
                        },
                        new
                        {
                            QId = "DM3",
                            Qtext = "Are you able to make appropriate use of varied Digital Marketing Platforms like Email, Facebook, Twitter, YouTube, Pinterest, etc as per given scenario?",
                            SId = "MCA-128"
                        },
                        new
                        {
                            QId = "DM4",
                            Qtext = "Are you able to apply and analyze the concept of Search Engine Optimization (SEO), SEM and Mobile Marketing to given scenarios?",
                            SId = "MCA-128"
                        },
                        new
                        {
                            QId = "DM5",
                            Qtext = "Are you able to analyze specific trends using Google Analytics?",
                            SId = "MCA-128"
                        },
                        new
                        {
                            QId = "DM6",
                            Qtext = "Are you able to create effective Display Ads and Search Engine Advertising",
                            SId = "MCA-128"
                        },
                        new
                        {
                            QId = "DFSL1",
                            Qtext = "Are you able to illustrate basic data structures- arrays and linked lists?",
                            SId = "MCA-162"
                        },
                        new
                        {
                            QId = "DFSL2",
                            Qtext = "Are you able to build stacks and queues using arrays and linked lists?",
                            SId = "MCA-162"
                        },
                        new
                        {
                            QId = "DFSL3",
                            Qtext = "Are you able to discover sparse matrix, polynomial arithmetic, searching and sorting techniques and their applications?",
                            SId = "MCA-162"
                        },
                        new
                        {
                            QId = "DFSL4",
                            Qtext = "Are you able to appraise binary search tree to perform efficient search operations ? ",
                            SId = "MCA-162"
                        },
                        new
                        {
                            QId = "DFSL5",
                            Qtext = "Are you able to examine and implement graph algorithms?",
                            SId = "MCA-162"
                        },
                        new
                        {
                            QId = "DFSL6",
                            Qtext = "Are you able to develop an application making extensive use of binary files?",
                            SId = "MCA-162"
                        },
                        new
                        {
                            QId = "OOSEL1",
                            Qtext = "Are you able to apply object-oriented software engineering concepts to a project?",
                            SId = "MCA-164"
                        },
                        new
                        {
                            QId = "OOSEL2",
                            Qtext = "Are you able to build design model diagrams for design phase?",
                            SId = "MCA-164"
                        },
                        new
                        {
                            QId = "OOSEL3",
                            Qtext = "Are you able to analyze and construct models and diagrams in analysis phase?",
                            SId = "MCA-164"
                        },
                        new
                        {
                            QId = "OOSEL4",
                            Qtext = "Are you able to appraise an advanced CASE tool?",
                            SId = "MCA-164"
                        },
                        new
                        {
                            QId = "OOSEL5",
                            Qtext = "Are you able to design and deploy a project suitably?",
                            SId = "MCA-164"
                        },
                        new
                        {
                            QId = "OOSEL6",
                            Qtext = "Are you able to work in teams to design practical solutions for real life case studies using UML?",
                            SId = "MCA-164"
                        },
                        new
                        {
                            QId = "PPL1",
                            Qtext = "Are you able to demonstrate program creation in Python through usage of appropriate constructs and OOPs concepts?",
                            SId = "MCA-166"
                        },
                        new
                        {
                            QId = "PPL2",
                            Qtext = "Are you able to apply the concepts of data structures and string functions in python program?",
                            SId = "MCA-166"
                        },
                        new
                        {
                            QId = "PPL3",
                            Qtext = "Are you able to apply the concepts of file handling and exception handling?",
                            SId = "MCA-166"
                        },
                        new
                        {
                            QId = "PPL4",
                            Qtext = "Are you able to evaluate and visualize the data using appropriate python libraries?",
                            SId = "MCA-166"
                        },
                        new
                        {
                            QId = "PPL5",
                            Qtext = "Are you able to work in teams to develop GUI based applications with database connectivity in Python?",
                            SId = "MCA-166"
                        },
                        new
                        {
                            QId = "STL1",
                            Qtext = "Are you able to plan and test driven development within the context of a software development application?",
                            SId = "STMCA-168"
                        },
                        new
                        {
                            QId = "STL2",
                            Qtext = "Are you able to discover specific and measurable test cases and suites to ensure coverage and traceability to requirements through appropriate tools?",
                            SId = "STMCA-168"
                        },
                        new
                        {
                            QId = "STL3",
                            Qtext = "Are you able to appraise and prioritize test cases for the specific software?",
                            SId = "STMCA-168"
                        },
                        new
                        {
                            QId = "STL4",
                            Qtext = "Are you able to evaluate problem reporting techniques, metrics, and testing status reports to communicate testing results to colleagues, managers and end users?",
                            SId = "STMCA-168"
                        },
                        new
                        {
                            QId = "STL5",
                            Qtext = "Are you able to work in teams to adapt in a team to design a live case study on a software product through appropriate agile methodology?",
                            SId = "STMCA-168"
                        },
                        new
                        {
                            QId = "MP21",
                            Qtext = "Are you able to Apply acquired knowledge within the chosen technology for solution of specific real world problem.",
                            SId = "MCA-170"
                        },
                        new
                        {
                            QId = "MP22",
                            Qtext = "Are you able to Analyze the technical aspects of the chosen project through a systematic and comprehensive approach.",
                            SId = "MCA-170"
                        },
                        new
                        {
                            QId = "MP23",
                            Qtext = "Are you able to Deduct plausible solution for the technical aspects of the project.",
                            SId = "MCA-170"
                        },
                        new
                        {
                            QId = "MP24",
                            Qtext = "Are you able to Work as an individual or in teams to develop the technical project.",
                            SId = "MCA-170"
                        },
                        new
                        {
                            QId = "MP25",
                            Qtext = "Are you able to Create effective reports and documentation for all project related activities and solutions.",
                            SId = "MCA-170"
                        },
                        new
                        {
                            QId = "AIMLL1",
                            Qtext = "Are you able to Apply heuristic search based algorithms to solve different puzzles.",
                            SId = "MCA-263"
                        },
                        new
                        {
                            QId = "AIMLL2",
                            Qtext = "Are you able to Identify reduction techniques on large datasets and reduce their dimensionality.",
                            SId = "MCA-263"
                        },
                        new
                        {
                            QId = "AIMLL3",
                            Qtext = "Are you able to Analyze the datasets for bias and apply appropriate regression techniques.",
                            SId = "MCA-263"
                        },
                        new
                        {
                            QId = "AIMLL4",
                            Qtext = "Are you able to Evaluate the learning techniques for classification.",
                            SId = "MCA-263"
                        },
                        new
                        {
                            QId = "AIMLL5",
                            Qtext = "Are you able to Implement the knowledge of inferences rules to design the knowledge base.",
                            SId = "MCA-263"
                        },
                        new
                        {
                            QId = "AIMLL6",
                            Qtext = "re you able to Create a domain specific intelligent application.",
                            SId = "MCA-263"
                        },
                        new
                        {
                            QId = "EBSL1",
                            Qtext = "Are you able to Model an appropriate Business model for a proposed website",
                            SId = "EBMCA-265"
                        },
                        new
                        {
                            QId = "EBSL2",
                            Qtext = "Are you able to Distinguish varied online payment methods",
                            SId = "EBMCA-265"
                        },
                        new
                        {
                            QId = "EBSL3",
                            Qtext = "Are you able to Assess varied e-commerce software's",
                            SId = "EBMCA-265"
                        },
                        new
                        {
                            QId = "EBSL4",
                            Qtext = "Are you able to Create an e-commerce website and compare it with similar existing websites",
                            SId = "EBMCA-265"
                        },
                        new
                        {
                            QId = "CCL1",
                            Qtext = "Are you able to Demonstrate the cloud platform on an appropriate tool.",
                            SId = "CCMCA-265"
                        },
                        new
                        {
                            QId = "CCL2",
                            Qtext = "Are you able to Apply virtualization in clouds.",
                            SId = "CCMCA-265"
                        },
                        new
                        {
                            QId = "CCL3",
                            Qtext = "Are you able to Distinguish between at least two cloud- based platforms.",
                            SId = "CCMCA-265"
                        },
                        new
                        {
                            QId = "CCL4",
                            Qtext = "Are you able to Choose and implement best security practices of cloud.",
                            SId = "CCMCA-265"
                        },
                        new
                        {
                            QId = "CCL5",
                            Qtext = "Are you able to Create automation on load balancing in cloud.",
                            SId = "CCMCA-265"
                        },
                        new
                        {
                            QId = "MP31",
                            Qtext = "Are you able to Apply acquired knowledge within the chosen technology for solution of specific problem.",
                            SId = "MCA-269"
                        },
                        new
                        {
                            QId = "MP32",
                            Qtext = "Are you able to Analyze the technical aspects of the chosen project through a systematic and comprehensive approach.",
                            SId = "MCA-269"
                        },
                        new
                        {
                            QId = "MP33",
                            Qtext = "Are you able to Deduct plausible solution for the technical aspects of the project.",
                            SId = "MCA-269"
                        },
                        new
                        {
                            QId = "MP34",
                            Qtext = "Are you able to Work as an individual or in teams to develop the technical project.",
                            SId = "MCA-269"
                        },
                        new
                        {
                            QId = "MP35",
                            Qtext = "Are you able to Create effective reports and documentation for all project related activities and solutions.",
                            SId = "MCA-269"
                        },
                        new
                        {
                            QId = "MML1",
                            Qtext = "Are you able to Demonstrate modelling of 2D and 3D graphical scenes using Open Graphics Library suits.",
                            SId = "MTMCA-267"
                        },
                        new
                        {
                            QId = "MML2",
                            Qtext = "Are you able to Apply various delivery methods including streaming.",
                            SId = "MTMCA-267"
                        },
                        new
                        {
                            QId = "MML3",
                            Qtext = "Are you able to Analyse audio and text compression algorithms.",
                            SId = "MTMCA-267"
                        },
                        new
                        {
                            QId = "MML4",
                            Qtext = "Are you able to Examine video compression algorithms.",
                            SId = "MTMCA-267"
                        },
                        new
                        {
                            QId = "MML5",
                            Qtext = "Are you able to Create 2D animation applications using appropriate multimedia tools.",
                            SId = "MTMCA-267"
                        },
                        new
                        {
                            QId = "MML6",
                            Qtext = "Are you able to Develop customized multimedia projects using different components.",
                            SId = "MTMCA-267"
                        },
                        new
                        {
                            QId = "SDAL1",
                            Qtext = "Are you able to Identify various measures like Central tendency, Measures of Dispersion, Measures of shape etc.",
                            SId = "StatsMCA-265"
                        },
                        new
                        {
                            QId = "SDAL2",
                            Qtext = "Are you able to Analyze Probability Distribution on specific cases",
                            SId = "StatsMCA-265"
                        },
                        new
                        {
                            QId = "SDAL3",
                            Qtext = "Are you able to Assess hypothesis testing and apply inferential statistics- t, F, Z and Chi Square Test to specific cases",
                            SId = "StatsMCA-265"
                        },
                        new
                        {
                            QId = "SDAL4",
                            Qtext = "Are you able to Deduct Correlation and Regression on specific problems.",
                            SId = "StatsMCA-265"
                        },
                        new
                        {
                            QId = "SDAL5",
                            Qtext = "Are you able to Elaborate Statistical and Data analytics techniques on real time data (case study).",
                            SId = "StatsMCA-265"
                        },
                        new
                        {
                            QId = "DAAL1",
                            Qtext = "Are you able to Apply logical thinking to build solutions for given problems.",
                            SId = "MCA-261"
                        },
                        new
                        {
                            QId = "DAAL2",
                            Qtext = "Are you able to Evaluate correctness & efficiency of algorithms using inductive proofs and invariants.",
                            SId = "MCA-261"
                        },
                        new
                        {
                            QId = "DAAL3",
                            Qtext = "Are you able to Design and perform parameter-based analysis of the searching, sorting and tree-based algorithms.",
                            SId = "MCA-261"
                        },
                        new
                        {
                            QId = "DAAL4",
                            Qtext = "Are you able to Create and test optimal solutions for various problems.",
                            SId = "MCA-261"
                        },
                        new
                        {
                            QId = "CSCL1",
                            Qtext = "Are you able to Demonstrate computer technologies, digital evidence collection, and reporting in forensic acquisition.",
                            SId = "MCA-253"
                        },
                        new
                        {
                            QId = "CSCL2",
                            Qtext = "Are you able to Apply strategies of using information as a weapon and a target.",
                            SId = "MCA-253"
                        },
                        new
                        {
                            QId = "CSCL3",
                            Qtext = "Are you able to Identify the principles of offensive and defensive information warfare for a given context.",
                            SId = "MCA-253"
                        },
                        new
                        {
                            QId = "CSCL4",
                            Qtext = "Are you able to Analyze the social, legal and ethical implications of information warfare.",
                            SId = "MCA-253"
                        },
                        new
                        {
                            QId = "CSCL5",
                            Qtext = "Are you able to Appraise key terms and concepts in cyber law, intellectual property and cyber crimes, trademarks, domain theft and Cyber Forensics.",
                            SId = "MCA-253"
                        },
                        new
                        {
                            QId = "MM1",
                            Qtext = "Are you able to Explain the technical aspects of multimedia systems.",
                            SId = "MCA-233"
                        },
                        new
                        {
                            QId = "MM2",
                            Qtext = "Are you able to Apply various file formats of audio, video and text media in different applications.",
                            SId = "MCA-233"
                        },
                        new
                        {
                            QId = "MM3",
                            Qtext = "Are you able to Analyze the QoS parameters of various multimedia applications through internet.",
                            SId = "MCA-233"
                        },
                        new
                        {
                            QId = "MM4",
                            Qtext = "Are you able to Evaluate different types of multimedia compression methods.",
                            SId = "MCA-233"
                        },
                        new
                        {
                            QId = "MM5",
                            Qtext = "Are you able to Design interactive multimedia software applications using animations.",
                            SId = "MCA-233"
                        },
                        new
                        {
                            QId = "MM6",
                            Qtext = "Are you able to Develop real-time multimedia applications using different multimedia components.",
                            SId = "MCA-233"
                        },
                        new
                        {
                            QId = "EBS1",
                            Qtext = "Are you able to Define the concepts of e-business and e- commerce and the related information technology and web-based tools.",
                            SId = "MCA-225"
                        },
                        new
                        {
                            QId = "EBS2",
                            Qtext = "Are you able to Identify Security aspects of e-business-online threats, security protocols and understand and apply cryptographic applications for securing the e-businesses and data privacy.",
                            SId = "MCA-225"
                        },
                        new
                        {
                            QId = "EBS3",
                            Qtext = "Are you able to Examine various e-business models, revenue models, electronic payment systems and electronic fund transfers.",
                            SId = "MCA-225"
                        },
                        new
                        {
                            QId = "EBS4",
                            Qtext = "Are you able to Create effective strategies for e-business, and mobile commerce while adapting to the emerging trends in e-business.",
                            SId = "MCA-225"
                        },
                        new
                        {
                            QId = "CC1",
                            Qtext = "Are you able to Identify the importance of Cloud Computing Paradigm, Cloud Security primitives & Load Configurations.",
                            SId = "MCA-223"
                        },
                        new
                        {
                            QId = "CC2",
                            Qtext = "Are you able to Model and apply the concepts of Virtualization and Security in the cloud computing environment.",
                            SId = "MCA-223"
                        },
                        new
                        {
                            QId = "CC3",
                            Qtext = "Are you able to Analyze the concept of Data Centres with Cloud Computing and examine the Use cases of various Cloud Computing Titans.",
                            SId = "MCA-223"
                        },
                        new
                        {
                            QId = "CC4",
                            Qtext = "Are you able to Design & Appraise Cloud Computing based VMS and weigh the advantages & disadvantages of various proprietary platforms along with available best practices.",
                            SId = "MCA-223"
                        },
                        new
                        {
                            QId = "SDA1",
                            Qtext = "Are you able to Explain fundamental concepts and terminologies of statistics and data analytics",
                            SId = "MCA-205"
                        },
                        new
                        {
                            QId = "SDA2",
                            Qtext = "Are you able to Experiment with various measures of central tendency, dispersion, shape and their implication.",
                            SId = "MCA-205"
                        },
                        new
                        {
                            QId = "SDA3",
                            Qtext = "Are you able to Apply probability and probability distribution primitives.",
                            SId = "MCA-205"
                        },
                        new
                        {
                            QId = "SDA4",
                            Qtext = "Are you able to Examine hypothesis testing and use inferential statistics- T, F, Z and Chi Square Test",
                            SId = "MCA-205"
                        },
                        new
                        {
                            QId = "SDA5",
                            Qtext = "Are you able to Assess analysis of variance for specific cases.",
                            SId = "MCA-205"
                        },
                        new
                        {
                            QId = "AIML1",
                            Qtext = "Are you able to Define the meaning of Intelligence and recall various models for knowledge representation and reasoning within an AI problem domain.",
                            SId = "MCA-203"
                        },
                        new
                        {
                            QId = "AIML2",
                            Qtext = "Are you able to Summarize varied learning algorithms and model selection.",
                            SId = "MCA-203"
                        },
                        new
                        {
                            QId = "AIML3",
                            Qtext = "Are you able to Apply the concept of learning trends and patterns from data to build an appreciation for what is involved in learning from data.",
                            SId = "MCA-203"
                        },
                        new
                        {
                            QId = "AIML4",
                            Qtext = "Are you able to Analyze and apply a variety of learning algorithms to data.",
                            SId = "MCA-203"
                        },
                        new
                        {
                            QId = "AIML5",
                            Qtext = "Are you able to Appraise AI algorithms and assess their performance. Follow standards and ethical practices.",
                            SId = "MCA-203"
                        },
                        new
                        {
                            QId = "AIML6",
                            Qtext = "Are you able to Develop a strong foundation for a wide variety of state of the art Machine Learning algorithms.",
                            SId = "MCA-203"
                        },
                        new
                        {
                            QId = "DAA1",
                            Qtext = "Are you able to Demonstrate P and NP complexity classes of the problem.",
                            SId = "MCA-201"
                        },
                        new
                        {
                            QId = "DAA2",
                            Qtext = "Are you able to Apply the concepts of asymptotic notations to analyze the complexities of various algorithms.",
                            SId = "MCA-201"
                        },
                        new
                        {
                            QId = "DAA3",
                            Qtext = "Are you able to Analyze and evaluate the searching, sorting and tree-based algorithms.",
                            SId = "MCA-201"
                        },
                        new
                        {
                            QId = "DAA4",
                            Qtext = "Are you able to Design efficient solutions using various algorithms for given problems.",
                            SId = "MCA-201"
                        },
                        new
                        {
                            QId = "DAA5",
                            Qtext = "Are you able to Develop innovative solutions for real-world problems using different paradigms.",
                            SId = "MCA-201"
                        },
                        new
                        {
                            QId = "DMP1",
                            Qtext = "Are you able to Apply techniques, skills and modern computing tools necessary for project development.",
                            SId = "MCA-202"
                        },
                        new
                        {
                            QId = "DMP2",
                            Qtext = "Are you able to Apply team-skills, ethics and professional attitude in professional endeavour.",
                            SId = "MCA-202"
                        },
                        new
                        {
                            QId = "DMP3",
                            Qtext = "Are you able to Model overall project management through sustainable practices.",
                            SId = "MCA-202"
                        },
                        new
                        {
                            QId = "DMP4",
                            Qtext = "Are you able to Adapt technological changes and futuristic challenges of the contemporary world.",
                            SId = "MCA-202"
                        },
                        new
                        {
                            QId = "DMP5",
                            Qtext = "Are you able to Create technical documents and reports.",
                            SId = "MCA-202"
                        },
                        new
                        {
                            QId = "PO1",
                            Qtext = "Demonstrate competencies in fundamentals of computing, computing specialization, mathematics and domain knowledge suitable for the computing specialization to the abstraction and conceptualization of computing models from defined problems and requirements.",
                            SId = "PO"
                        },
                        new
                        {
                            QId = "PO2",
                            Qtext = "Identify, formulate and analyze complex real-life problems in order to arrive at computationally viable conclusions using fundamentals of mathematics, computer sciences, management and relevant domain disciplines.",
                            SId = "PO"
                        },
                        new
                        {
                            QId = "PO3",
                            Qtext = "Design efficient solutions for complex, real-world problems to design systems, components or processes that meet the specifications with suitable consideration to public health, safety, cultural, societal and environmental considerations.",
                            SId = "PO"
                        },
                        new
                        {
                            QId = "PO4",
                            Qtext = "Ability to research, analyze and investigate complex computing problems through design of experiments, analysis and interpretation of data and synthesis of the information to arrive at valid conclusions.",
                            SId = "PO"
                        },
                        new
                        {
                            QId = "PO5",
                            Qtext = "Create, select, adapt and apply appropriate technologies and tools to a wide range of computational activities while understanding their limitations",
                            SId = "PO"
                        },
                        new
                        {
                            QId = "PO6",
                            Qtext = "Ability to perform professional practices in an ethical way, keeping in the mind cyber regulations & laws, responsibilities and norms of professional computing practices.",
                            SId = "PO"
                        },
                        new
                        {
                            QId = "PO7",
                            Qtext = "Ability to engage in independent learning for continuous self- development as a computing professional.",
                            SId = "PO"
                        },
                        new
                        {
                            QId = "PO8",
                            Qtext = "Ability to apply knowledge and understanding of the computing and management principles and apply these to one's own work, as a member and leader in a team, to manage projects in multidisciplinary environments.",
                            SId = "PO"
                        },
                        new
                        {
                            QId = "PO9",
                            Qtext = "Ability to effectively communicate with the technical community and with the society at large about complex computing activities by being able to understand and write effective reports, design documentation, make effective presentations with the capability of giving and taking clear instructions.",
                            SId = "PO"
                        },
                        new
                        {
                            QId = "PO10",
                            Qtext = "Ability to recognize and assess societal, environmental, health, safety, legal and cultural issues within local and global contexts and the consequential responsibilities applicable to professional computing practices.",
                            SId = "PO"
                        },
                        new
                        {
                            QId = "PO11",
                            Qtext = "Ability to work in multi-disciplinary team collaboration both as a member and leader, as per need.",
                            SId = "PO"
                        },
                        new
                        {
                            QId = "PO12",
                            Qtext = "Ability to apply innovation to track a suitable opportunity to create value and wealth for the betterment of the individual and society at large.",
                            SId = "PO"
                        },
                        new
                        {
                            QId = "CN1",
                            Qtext = "Are you able to Explain the functions of each layer in the OSI reference model and TCP/IP protocol suite while illustrating the process of data encoding and multiplexing.",
                            SId = "PO"
                        },
                        new
                        {
                            QId = "CN2",
                            Qtext = "Are you able to Utilize the fundamentals of data communication and networking to identify the topologies and connecting devices of networks.",
                            SId = "PO"
                        },
                        new
                        {
                            QId = "CN3",
                            Qtext = "Are you able to Identify and discuss the underlying concepts of IPv4 & IPv6 protocols, along with their characteristics and functionality.",
                            SId = "PO"
                        },
                        new
                        {
                            QId = "CN4",
                            Qtext = "Are you able to Discover the appropriate MAC layer/ data link layer protocols for the given network.",
                            SId = "PO"
                        },
                        new
                        {
                            QId = "CN5",
                            Qtext = "Are you able to Evaluate and implement routing algorithms and multicasting.",
                            SId = "PO"
                        },
                        new
                        {
                            QId = "CN6",
                            Qtext = "Are you able to Adapt transport and application layer protocols along with concepts of mobility and security in networks.",
                            SId = "PO"
                        });
                });

            modelBuilder.Entity("CourseOutcome.Models.Response", b =>
                {
                    b.Property<string>("Enrollmentno")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Response1")
                        .HasColumnType("int");

                    b.Property<int?>("Response2")
                        .HasColumnType("int");

                    b.Property<int?>("Response3")
                        .HasColumnType("int");

                    b.Property<int?>("Response4")
                        .HasColumnType("int");

                    b.Property<int?>("Response5")
                        .HasColumnType("int");

                    b.Property<int?>("Response6")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmissionTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Suggestion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Enrollmentno", "SId");

                    b.HasIndex("SId");

                    b.ToTable("Response");
                });

            modelBuilder.Entity("CourseOutcome.Models.Subject", b =>
                {
                    b.Property<string>("SId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SId");

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            SId = "MCA-103",
                            SubjectName = "Computer Networks"
                        },
                        new
                        {
                            SId = "MCA-105",
                            SubjectName = "Operating Systems with Linux"
                        },
                        new
                        {
                            SId = "MCA-107",
                            SubjectName = "Database Management Systems"
                        },
                        new
                        {
                            SId = "MCA-109",
                            SubjectName = "Object Oriented Programming and JAVA"
                        },
                        new
                        {
                            SId = "MCA-161",
                            SubjectName = "Computer Networks Lab."
                        },
                        new
                        {
                            SId = "MCA-163",
                            SubjectName = "Operating Systems with Linux Lab."
                        },
                        new
                        {
                            SId = "MCA-165",
                            SubjectName = "Database Management Systems Lab."
                        },
                        new
                        {
                            SId = "MCA-167",
                            SubjectName = "Object Oriented Programming and JAVA Lab."
                        },
                        new
                        {
                            SId = "MCA-169",
                            SubjectName = "Minor Project I"
                        },
                        new
                        {
                            SId = "MCA-101",
                            SubjectName = "Discrete Structures"
                        },
                        new
                        {
                            SId = "FSDMCA-168",
                            SubjectName = "Full Stack Development Lab"
                        },
                        new
                        {
                            SId = "MCA-102",
                            SubjectName = "Data and File Structures"
                        },
                        new
                        {
                            SId = "MCA-104",
                            SubjectName = "Object Oriented Software Engineering"
                        },
                        new
                        {
                            SId = "MCA-106",
                            SubjectName = "Python Programming"
                        },
                        new
                        {
                            SId = "MCA-114",
                            SubjectName = "Full Stack Development"
                        },
                        new
                        {
                            SId = "MCA-120",
                            SubjectName = "Software Testing"
                        },
                        new
                        {
                            SId = "MCA-128",
                            SubjectName = "Digital Marketing"
                        },
                        new
                        {
                            SId = "MCA-162",
                            SubjectName = "Data and File Structures Lab"
                        },
                        new
                        {
                            SId = "MCA-164",
                            SubjectName = "Object Oriented Software Engineering Lab"
                        },
                        new
                        {
                            SId = "MCA-166",
                            SubjectName = "Python Programming Lab"
                        },
                        new
                        {
                            SId = "STMCA-168",
                            SubjectName = "Software Testing Lab"
                        },
                        new
                        {
                            SId = "MCA-170",
                            SubjectName = "Minor Project II"
                        },
                        new
                        {
                            SId = "MCA-263",
                            SubjectName = "Artificial Intelligence and Machine Learning Lab."
                        },
                        new
                        {
                            SId = "EBMCA-265",
                            SubjectName = "Lab e-Business Systems"
                        },
                        new
                        {
                            SId = "CCMCA-265",
                            SubjectName = "Lab Cloud Computing"
                        },
                        new
                        {
                            SId = "MCA-269",
                            SubjectName = "Minor Project III"
                        },
                        new
                        {
                            SId = "MTMCA-267",
                            SubjectName = "Lab Multimedia Technologies"
                        },
                        new
                        {
                            SId = "StatsMCA-265",
                            SubjectName = "Lab Statistics and Data Analytics"
                        },
                        new
                        {
                            SId = "MCA-261",
                            SubjectName = "Design and Analysis of Algorithms Lab."
                        },
                        new
                        {
                            SId = "MCA-253",
                            SubjectName = "Cyber Security and Cyber Laws"
                        },
                        new
                        {
                            SId = "MCA-233",
                            SubjectName = "Multimedia Technologies"
                        },
                        new
                        {
                            SId = "MCA-225",
                            SubjectName = "e-Business Systems"
                        },
                        new
                        {
                            SId = "MCA-223",
                            SubjectName = "Cloud Computing"
                        },
                        new
                        {
                            SId = "MCA-205",
                            SubjectName = "Statistics and Data Analytics"
                        },
                        new
                        {
                            SId = "MCA-203",
                            SubjectName = "Artificial Intelligence and Machine Learning"
                        },
                        new
                        {
                            SId = "MCA-201",
                            SubjectName = "Design and Analysis of Algorithms"
                        },
                        new
                        {
                            SId = "MCA-202",
                            SubjectName = "Dissertation (Major Project)"
                        },
                        new
                        {
                            SId = "PO",
                            SubjectName = "Program Outcome"
                        });
                });

            modelBuilder.Entity("CourseOutcome.Models.Question", b =>
                {
                    b.HasOne("CourseOutcome.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("CourseOutcome.Models.Response", b =>
                {
                    b.HasOne("CourseOutcome.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });
#pragma warning restore 612, 618
        }
    }
}
